export const INIT_ROW_DATA = 'INIT_ROW_DATA';
export const GET_SORT_MODEL = 'GET_SORT_MODEL'
export const GET_FILTER_MODEL = 'GET_FILTER_MODEL'
export const SET_SORT_MODEL = 'SET_SORT_MODEL'
export const SET_FILTER_MODEL = 'SET_FILTER_MODEL'

